#!/bin/bash

# ripgrep is a line-oriented search tool that recursively searches the current
# directory for a regex pattern. By default, ripgrep will respect gitignore rules and
# automatically skip hidden files/directories and binary files. (To disable all
# automatic filtering by default, use rg -uuu.) ripgrep is similar to other popular
# search tools like The Silver Searcher, ack and grep.
#
# Site: https://github.com/BurntSushi/ripgrep
# Docs: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md

# Install ripgrep
sudo apt install -y ripgrep
